= THE DEATH AND SUCCESSOR OF MOSES

== The Death of Moses
    Knowing that Moses was very old and that he could die at any time, thoughtful Israelites must have been concerned about God's people and about God's move with His people. They might have said to themselves: "What will happen when Moses is gone? Who will be his successor?"

    Instead of justifying our worry, He might say: "Be at peace. Do not worry about the turmoil. I know the situation."

[]
. Jehovah Telling Moses to Go Up to the Mountain of Abarim and See the Land-Moses could only see the land; he was not permitted to enter into it.

. Moses to Be Gathered to His Forefathers
    This gathering was somewhat like a harvesting. Moses was "ripe," and soon he was to be "harvested." This gathering, this harvesting, was to be the end of Moses' life.

. Moses Having Rebelled against God's Word

    Moses could not enter into the good land because, in the wilderness of Zin, he had rebelled against God's word to sanctify Him at the waters before the eyes of Israel (v. 14; 20:10-13). Moses had acted contrary to God's nature and God's economy. This serious failure caused him to lose the right to enter into the land of Canaan. However, the fact that Moses could not enter into the good land because of this failure does not mean that he will not be in the millennial kingdom. Matthew 16:28—17:4 indicates that Moses will surely be in the kingdom.

    Due to his failure, his ending was not glorious, but his ministry certainly was glorious.
    
== The Successor of Moses

. Moses Asking Jehovah to Appoint a Man over the Assembly of Israel

    Moses' concern was not for himself and for the loss of the right to enter into the land. He was not the kind of person who cared so much for himself and his situation. Although he was very old, he was concerned for God's people, realizing that they would be in need of a shepherd.

. Jehovah Telling Moses to Lay His Hand upon Joshua and Charge Him to Be His Successor

.. Joshua Being a Man in Whom the Spirit Was

.. Moses Bestowing Some of His Majesty upon Joshua-Majesty here signifies honor and glory.

.. Joshua to Stand before Eleazar the Priest, Who Would Inquire for Him by the Judgment of the Urim before Jehovah

    When God brought His people into the wilderness, He spoke to them through Moses. God spoke to Moses face to face. But Joshua, Moses' successor, was to receive guidance not from God by His direct speaking in the way He spoke to Moses, but by the Urim and the Thummim on the breastplate worn by Eleazar the priest. Whenever Joshua needed guidance concerning the move of the people, he had to go to the high priest, who then received guidance from God by means of the Urim and the Thummim.
    
    Although Joshua was made the leader, he did not have the right to receive the divine instructions directly. Instead, the high priest received God's instructions and then passed them on to Joshua, who was responsible for their execution.

	God's government among His people was a matter not of autocracy or democracy but theocracy. 

. Moses Doing as Jehovah Commanded Him
