= FURTHER FAILURES

. Contending for Water
	
	Because there was no water for the assembly, the people "gathered themselves together against Moses and against Aaron" (v. 2).

.. The People Contending with Moses with Evil Words

.. Moses and Aaron Leaving the Congregation, Going to the Entrance of the Tent of Meeting, and Falling on Their Faces

.. Jehovah Commanding Moses to Take the Rod and Speak to the Rock with Aaron before the People That the Rock Might Yield Its Water
	
	The rock typifies Christ (1 Cor. 10:4b), and the water typifies the Spirit (1 Cor. 10:4a).

.. Moses Taking the Rod, Calling the People Rebels, and Striking the Rock with His Rod Twice, and Water Coming Out Abundantly
	
	Whenever we are angry and do not control ourselves, it is easy for us to make mistakes. At such times we, like Moses, may speak wrongly or act wrongly.
	
	 Although Moses was a faithful servant of God, in Numbers 20 he made a mistake which caused him to lose his right to enter into the promised good land.

.. God Supplying the Israelites with Manna and Water to Meet Their Proper Need, without Any Punishment, but Supplying Them with Quails to Satisfy Their Lusting after the Flesh, as a Punishment
	
	When the children of Israel caused God trouble concerning necessities, He was not offended, but when they lusted, He was offended. Actually, it was His responsibility to supply them with water.

.. Moses Failing to Sanctify God in Being Angry with the People of Israel and in Wrongly Striking the Rock Twice
	
	In being angry, he did not represent God rightly in His holy nature toward His people. In striking the rock twice, he represented God wrongly in God's action. 
	
	 we should not pray when we are angry. we learn that we should be careful whenever we pray to God concerning His people.
	
	Because he was angry when God was not angry, Moses did not rightly represent God. 
	
	According to Moses' view in chapter twenty, there was much trouble and iniquity among God's people, but in God's view there was neither trouble nor iniquity. This means that although Moses was usually one with God, in this instance there was a great discrepancy between him and God.
	
	His mistaken speaking made God common; that is, it did not sanctify God, did not make Him separate from all other gods. 
	
	The people were not at fault for being thirsty, and they were not rebelling against Me. You condemned them as rebels, but you are the ones who rebelled against My word."
	
	We need to learn that, especially when we have been offended by the saints in the church, we should not go to God for the purpose of accusing His people. 

	He is not offended with His people when the lack of water causes them to contend. Even if He must punish His people, He punishes them sparingly. 
	
	We must not give people the wrong impression concerning the God whom we serve. 
	
	when Moses, in anger, acted wrongly, he broke the principles of God's economy. This should be a warning to us not to hold on to our anger but to practice Paul's word in Ephesians 4:26: "Do not let the sun go down on your indignation."

	Moses offended both God's holy nature and divine economy. He represented God wrongly, and he broke the principles of God's economy. 
	
	We should not offend other saints or stumble them. Whenever we are offended or stumbled, we should be forgiving. If we know only to condemn others and have no intention of forgiving them, we will have trouble. In the church life there is the need of forgiveness.

	The church life should be a forgiving life. Concerning the Bible we should have a good memory, but concerning others' wrongdoings we should have a poor memory. 
	
	The blunder committed by Moses in Numbers 20 consisted in not having a positive and pleasant feeling regarding God's people. 
	
	The lesson we need to learn from Moses' failure in Numbers 20 is that we should be very careful when we speak about God's people. We may think that we are right and that others are wrong. However, God may come in not to vindicate us but to vindicate the ones we condemn.
	
	Do not keep a record in your memory of others' offenses. Remembering offenses is risky, for it may cause you to lose your birthright, to lose your right to the enjoyment of Christ as the good land.
	
	From the type in this chapter, we may learn to have regard for God's nature and for His administration among His people. If we learn this lesson, we will be careful about speaking in a negative way concerning God's people.

7.. The Significance of the Types

	The problem in Numbers 20 was due to the lack of the Spirit of life. This indicates that whenever God's people are short of the Spirit of life, they will have trouble. 
	
	 To "take the rod" is to apply the death of Christ to ourselves. In striking the rock a second time, Moses made a serious mistake. This act was against God's economy. In God's economy Christ should not be crucified more than once.
	
	Christ was crucified under the rod of the law, and now He is the following rock, the life-giving Spirit.
	
	To have the living water, we simply need to take the rod and apply it to our situation today. We also need to speak to the rock. Speaking to the rock is a matter of believing. Furthermore, speaking to the rock indicates that we have prayed, not in the way of begging but in the way of believing that the Spirit has already been given.

	The problems in the church life are solved when we have an abundance of the Spirit of life. The problems between us and others and between us and God are due to our shortage of the Spirit of life. T
	
	it is not sufficient for us simply to be right with God; we must also be right in our attitude toward God's people. 
	
	In order to be right in our attitude, we must know God's nature. We need to realize that in His nature God is fair, bountiful, rich in supply, loving, gracious, and merciful. Whenever we see something in God's people which, to our view, is not right, we need to consider the situation according to God's nature. 
	
	To receive this supply, there is no need for us to beg or even to pray. We should simply speak a direct word to Christ as the smitten rock. 

	Today we do not need to beg Him for living water or wait for Him to supply us with water. We just need to come to Him and say, "Lord, I need Your Spirit. Lord, give me the Spirit of life." 

	Whenever we speak to Christ as the rock, telling Him to give us living water, we must have the rod in our hand. This means that as we speak to the rock, we must apply the death of Christ to ourselves and realize that we are crucified persons. 
	
. Speaking against God and Moses

.. Because the Way Was Hard, the People Being Impatient and Speaking against God and Moses, Mainly concerning the Food Supply
	
	From God's point of view, this contending, unlike the contending for water, was not fair. God had not promised that the way through the wilderness would be easy. They should have anticipated a difficult journey. Therefore, God was not happy with them and He punished them.

.. Jehovah Sending Fiery Serpents to Bite the People, so that Many of Them Died

.. The People Repenting to Moses and Asking Him to Pray That God Would Take Away the Serpents from Them
	
	In all their journeying, this is the first time the children of Israel confessed their sins. Having confessed their sin in speaking against God and Moses, they asked Moses to pray for them, and he did so.

.. Jehovah Commanding Moses to Make a Fiery Serpent and Set It on a Pole That Everyone Who Was Bitten Might Look at It and Live

	This bronze serpent typifies Christ (John 3:14), and the pole typifies the cross (1 Pet. 2:24). In typology bronze, or brass, signifies judgment. 

	In Numbers 20 we have a type of Christ as the crucified and resurrected One flowing out the all-inclusive, life-giving Spirit, but in Numbers 21 we have a type of Christ as our replacement and substitute.

	The bronze serpent on the pole indicated that the children of Israel, who had become serpentine, were put on the pole where they were replaced by something that had the form but not the nature of a serpent.

	If we are drinking of the living water, then we are no longer serpents. But if we are short of the living water, then we are contending serpents.
	
	Apart from the life-giving Spirit, we are contending serpents. In the church life we may be either contending serpents or life-giving-Spirit drinkers. May we all be those who drink of the all-inclusive, life-giving Spirit!