= rebellion

*took place immediately after the insertion with the instructions and warnings in chapter fifteen.*

== A MORE SERIOUS FAILURE

|===
|murmuring of evil|at the border of the camp
|lusting|mixed multitud
|speak against|two elder relatives
|unbelief in spying out the land|12 leaders
|rebellion|more than two hundred fifty people.
|===
=== A. who rebel
. Korah-a leader among the Levites
. Dathan, Abiram, and On- they lead among the sons of Israel according to their natural birth
. Two Hundred Fifty Leaders of the Assembly-They had been chosen from the congregation and were well-known men

=== B. The Cause of the Rebellion
. The Struggle for Position and Power
. The Accusation

=== C. The Reaction of Moses
. Falling on His Face
. Standing on the Position of God's Deputy Authority-He rebuked Korah and all his company and charged them to be present before Jehovah with their censers, referred this case to God as the highest authority for His speaking, exposure, and judgment.
. Being Very Angry-Here it seems that Moses was forced to vindicate himself, but God did not condemn him for this.
. Sending to Call Dathan and Abiram
.. they would not come up
.. Ambition is a "gopher" that undermines God's plan and damages His people.
.. I admire Moses' boldness in confronting this problem. 
.. because he was the target, it was difficult for him to say anything concerning himself without vindicating, and it was difficult to say anything about others without condemning. So the best way, he said, was not to say anything.
.. Even though Brother Nee was the one under attack, it was the church that was damaged, and it was God's plan that was hurt.
.. The ambition for power and the struggle for power are in our blood. This ambition and struggle can be found not only among males but also among females.
.. At a very crucial time, when the Lord told His followers what would happen to Him (Matt. 20:17-19). They heard Him, but they neither listened to what He said nor cared about it. 
.. If you read through the Acts and the Epistles, you will see that this struggle for power was there from the beginning of the church life. 
.. The history of Christianity is a history of the struggle for power. This struggle is within each one of us. You may not realize it, but it is hidden inside you. 
.. Consider the rebels among the children of Israel in Numbers. we must believe that the struggle for power was in every one of the sons of Israel.
.. The elders know that if they serve in a certain local church for several years, they will surely offend others. 
.. Those in the church life or in the Lord's work who are somewhat in the position of taking the lead will unavoidably offend some who are greedy for power.
.. Although he fell on his face, he still did something. He brought this matter openly to God, to let God come in to speak, to judge, and to vindicate.
.. they accused Moses. 
.. What should we do in this kind of situation? it is better not to do anything. The Lord is still living. He is still on the throne and is still sovereign. He is the sovereign Lord and the highest authority. 
.. But by His mercy we are here. 

*In this message we will see how God judged this rebellion*

=== D. God's Judgment
* No matter what is happening on earth, God's government still stands.
* In chapter sixteen of Numbers, God's judgment is threefold, coming from the earth, from heaven, and from within the people themselves. 

[]

. Korah Gathering All the Assembly against Moses and Aaron-This forced God to come out and appear in His glory to all the assembly. 
. God is the God not of the flesh of people but of their spirit.
. Korah, Dathan, and Abiram, Together with Their Wives, Their Sons, and Their Little Ones, and All the Men That Belonged to Korah and All Their Goods, Being Swallowed by the Earth and Going Down Alive into Sheol
.. Korah, Dathan, and Abiram were not afraid because of what they had done. The fact that their tents were close together indicates that they were very intimate. 
.. Probably this is the only time that living people were punished in such a way.
. Fire Coming Forth from Jehovah and Consuming the Two Hundred Fifty Men Offering the Incense
.. By this we can see that the rebellion was quite popular, even universal. Immediately after the three leaders were swallowed up alive by the earth, fire came forth from Jehovah and consumed the two hundred fifty men while they were offering incense (v. 35). This was the second aspect of God's judgment.
. The Censers of the Two Hundred Fifty Men Being Holy and Being Made into Hammered Plates as a Covering for the Altar
.. When the people came to offer at the altar, they were reminded of the rebellion and of God's judgment on Korah and his company.
. The Exposure of the Unsubdued Rebellious Nature of the People of Israel
.. On the Next Day All the Assembly of the Sons of Israel Murmuring against Moses and Aaron
.. God's Intervening-His glory appeared in the cloud that covered the tent of meeting The germs of the plague were probably in them already.
.. The Propitiation for the Sons of Israel through Moses and Aaron
... At this juncture, Moses and Aaron did something as an emergency measure. Nevertheless, fourteen thousand seven hundred of the people were killed. 
... However, even after the third judgment the people still complained
... God's judgment does not subdue people; rather, it consumes them.
... For God to forgive is one thing, and for Him to punish is another. In a particular situation God forgives, but He forgives through punishment; hence, this is a forgiveness with punishment.
... We need to have a holy fear before God. We should bow down and humble ourselves before Him and pray, "Lord, have mercy on me. Only Your mercy can preserve me and keep me in Your grace."

*In Numbers 17 we have God's vindication. Before we consider this matter, I would like to add a word concerning the descendants of Korah.*

. Numbers 16 seems to indicate that all of Korah's family, including his children, perished. But Numbers 26:11 tells us that the sons of Korah did not die.
. In 1 Chronicles 6:33-37, a record of the genealogy of Samuel, we are told that Samuel was a descendant of Korah. Samuel was not only a priest but also a great prophet.
. Furthermore, as the title of Psalm 88 indicates,a grandson of Samuel (1 Chron. 6:33). Heman was not only a psalmist but also a singer in the temple under David's arrangement.
. we can see that God is severe to some but merciful to others. Whether we experience His mercy or His severity depends on how we behave ourselves.

=== E. God's Vindication

* In chapter seventeen God went further to vindicate Aaron and Moses, His deputy authority, in a positive way.

[]
. After His Judgment, God Commanding That Twelve Rods Be Laid before the Testimony
.. This signifies that everything had to be brought into the presence of God to let God deal with the real situation by speaking the truth to all the people through His vindication. 
.. It was God's intention that this budding of a dead rod would cause the murmurings of the people to cease.
..  Sometimes, for His vindication, God puts us into a dark night, a dark tunnel, through which we must pass.
. Aaron's Rod Budding
.. Aaron's dead, dried up rod budded. This was an organic miracle.
.. Moses brought all the rods to all the sons of Israel, and they all looked (v. 9). The record indicates that, without saying a word and without praising the Lord for His vindication, each man took his rod.
. The Budding Rod of Aaron Being Put Back before the Testimony 
.. The budding rod of Aaron was put back before the testimony
.. To Be Kept as a Sign for the Sons of Rebellion
... Verse 5 refers to the murmurings as being against Moses, but verse 10 refers to them as being against God.
... whatever happened in the Old Testament on the positive side was related to Christ.
... Today He is still budding, and we are a small part, the fruit, the almonds, of His budding.
. The Rebellious Nature of the People of Israel Being Exposed to the Uttermost
..  This indicates that even after seeing God's judgment and vindication, the people were not subdued.
.. It is no wonder that these children of Israel were not permitted to enter the promised land. 
.. As chapter seventeen reveals, this case ends with the punished people not being subdued. Therefore, even God gave them up and let them go. They simply let the people be as they were. 
.. Do not expect to see an ending of turmoil. Although a particular storm will end, those who become involved in that storm may not cease their rebellion.
.. The rebellious nature in man is Satan himself. Only one person, Jesus Christ, who is the Son of God and also the Son of Man, can defeat this evil one, and He has defeated him (Heb. 2:14).
.. We have not only the Devil as the enemy on the outside but also Satan as the adversary on the inside. 
.. When Paul was about to be martyred, he wrote to Timothy, in his last Epistle, saying that all the people in Asia had left him 
.. We have emphasized the fact that, even after God's judgment and vindication, the children of Israel continued to speak words of rebellion. Numbers 17 portrays a sad picture concerning this rebellion. After seeing such a picture, we can only worship God, and worship Him as the Lord.

## note
. the people
.. Korah
.. Dathan, Abiram, and On
.. Two Hundred Fifty Leaders of the Assembly
. the reason
.. The Struggle for Position and Power
.. The Accusation:you take too much upon yourselves, for all the assembly are holy, every one of them , and jehoval is among them. why then do you exalt yourselves above the congregation of jehoval.
. mose's reaction
.. felling on his face
.. standing on the Position of God's Deputy Authority
... rebuke: you take too much upon yourselves
... charge: take cencers, referred this case to God
... them didn't come up, very angry: do not regard their offering
. god's reaction
.. judgement
... earth: the ground opens its mouth and swallows them up with all the belongs to them.
... heaven: fire came forth from jehovah and consumed the 250 men
... within the people: accuse mose, plague 14700
.. vindication[ˌvɪndɪ'keɪʃn]
... rod before testmoney
... rod budded produced blossom [ˈblɒsəm] bore ripe almonds[ˈɑ:məndz]
... rod put back testmoney, as a sign against the rebels
... expose the rebelious nature to the uttermost
. lessons
.. The ambition for power and the struggle for power are in our blood. This ambition and struggle can be found not only among males but also among females.
.. This struggle is within each one of us. You may not realize it, but it is hidden inside you.
.. Concerning ourselves, we need to realize that without the Lord's mercy and grace we might be the same as Korah, Dathan, and Abiram. But by His mercy we are here.
.. We need to be continually on the alert by watching and praying. We have not only the Devil as the enemy on the outside but also Satan as the adversary on the inside. 
.. one of his descendants became a priest, not by struggling for power but by being offered as a Nazarite. Samuel was not only a priest but also a great prophet.
.. a grandson of Samuel. Heman was not only a psalmist but also a singer in the temple under David's arrangement.

## speak