*took place immediately after the insertion with the instructions and warnings in chapter fifteen.*

== REBELLION—A MORE SERIOUS FAILURE

|===
|murmuring of evil|at the border of the camp
|lusting|mixed multitud
|speak against|two elder relatives
|unbelief in spying out the land|12 leaders
|rebellion|more than two hundred fifty people.
|===
=== A. who rebel.
. Korah-a leader among the Levites
. Dathan, Abiram, and On- they lead among the sons of Israel according to their natural birth
. Two Hundred Fifty Leaders of the Assembly-They had been chosen from the congregation and were well-known men

=== B. The Cause of the Rebellion
. The Struggle for Position and Power
. The Accusation

=== C. The Reaction of Moses
. Falling on His Face
. Standing on the Position of God's Deputy Authority-He rebuked Korah and all his company and charged them to be present before Jehovah with their censers, referred this case to God as the highest authority for His speaking, exposure, and judgment.
. Being Very Angry-Here it seems that Moses was forced to vindicate himself, but God did not condemn him for this.
. Sending to Call Dathan and Abiram
.. they would not come up
.. Ambition is a "gopher" that undermines God's plan and damages His people.
.. I admire Moses' boldness in confronting this problem. 
.. because he was the target, it was difficult for him to say anything concerning himself without vindicating, and it was difficult to say anything about others without condemning. So the best way, he said, was not to say anything.
.. Even though Brother Nee was the one under attack, it was the church that was damaged, and it was God's plan that was hurt.
.. The ambition for power and the struggle for power are in our blood. This ambition and struggle can be found not only among males but also among females.
.. At a very crucial time, when the Lord Jesus was going to Jerusalem to be crucified, He told His followers what would happen to Him (Matt. 20:17-19). They heard Him, but they neither listened to what He said nor cared about it. begging Him to put one on His right and one on His left in the kingdom (Matt. 20:20-28). The other disciples were indignant toward these two brothers. This indicates that there was a power struggle among the disciples.
.. If you read through the Acts and the Epistles, you will see that this struggle for power was there from the beginning of the church life. Ananias and Sapphira (Acts 5:1-4) were a couple who lied to God. Actually, their lying was a struggle for power. They wanted to be more important, to elevate themselves in the eyes of others. At the end of the Epistles, John mentioned one who was struggling for power, Diotrephes (3 John 9-11).
.. The history of Christianity is a history of the struggle for power. This struggle is within each one of us. You may not realize it, but it is hidden inside you. Eventually, the church life will be a test to our real situation. As long as we are in the church life, sooner or later we will be tested and exposed.
.. Consider the rebels among the children of Israel in Numbers. Some rebels were on the border of the camp, some were with the mixed multitude, and some were very close to Moses, the leading one. Now, in chapter sixteen, two hundred fifty leaders rebelled. In view of all this, we must believe that the struggle for power was in every one of the sons of Israel.
.. The elders know that if they serve in a certain local church for several years, they will surely offend others. 
.. Those in the church life or in the Lord's work who are somewhat in the position of taking the lead will unavoidably offend some who are greedy for power.
.. In chapter sixteen, Moses was bold and faithful in confronting a large-scale rebellion, a rebellion of two hundred fifty leaders. Although he fell on his face, he still did something. He brought this matter openly to God, to let God come in to speak, to judge, and to vindicate.
.. they accused Moses, saying that he had brought them out of a land of milk and honey (Egypt), that he had made himself a ruler over them, and that he had not brought them into a land flowing with milk and honey. Finally, they said, "Will you put out the eyes of these men? We will not come up" (v. 14). 
.. What should we do in this kind of situation? In such a rebellious situation, it is better not to do anything. The Lord is still living. He is still on the throne and is still sovereign. He is the sovereign Lord and the highest authority. He is the Head of the Body today. Thus, we must always refer these things to Him and let Him be what He is. This is all we can do, and this is what we must do.
.. Concerning ourselves, we need to realize that without the Lord's mercy and grace we might be the same as Korah, Dathan, and Abiram. But by His mercy we are here. Now we must learn to be alert and pray regarding any kind of rebellious situation.

*In this message we will see how God judged this rebellion*

=== D. God's Judgment
* No matter what is happening on earth, God's government still stands. we are assured that everything is under God's government. We must believe, therefore, that everything, including judgment, is under Him, up to Him, and in His hand.
* In chapter sixteen of Numbers, God's judgment is threefold, coming from the earth, from heaven, and from within the people themselves. The earth opened up to swallow certain of the rebellious ones, fire came from heaven to consume many others among the rebels, and germs from within others of the rebellious ones produced a plague that killed them.
. Korah Gathering All the Assembly against Moses and Aaron-This forced God to come out and appear in His glory to all the assembly. God's appearing in such a way was a very significant event.
. Jehovah Speaking to Moses and Aaron-Jehovah spoke to Moses and Aaron, telling them to separate themselves from among this assembly that He may consume the assembly in a moment (vv. 20-21). Then Moses and Aaron fell on their faces and said, "O God, the God of the spirits of all flesh, shall one man sin, and will You be angry with all the assembly?" (v. 22). God is the God not of the flesh of people but of their spirit.
. Korah, Dathan, and Abiram, Together with Their Wives, Their Sons, and Their Little Ones, and All the Men That Belonged to Korah and All Their Goods, Being Swallowed by the Earth and Going Down Alive into Sheol
.. Korah, Dathan, and Abiram were not afraid because of what they had done. They, together with their wives, their sons, and their little ones, came out and stood at the entrance of their tents (v. 27). The fact that their tents were close together indicates that they were very intimate. They belonged to different tribes—Korah, to the tribe of Levi, and Dathan and Abiram, to the tribe of Reuben—but they were quite close. When the earth opened up, they were all in the same place.
.. Korah, Dathan, and Abiram, together with their wives, their sons, and their little ones, and all the men who belonged to Korah and all their goods, were swallowed by the earth and sent down alive into Sheol (vv. 28-33). Sheol is a Hebrew word equivalent to the Greek word Hades. Sheol, or Hades, is the place where the souls and the spirits of the dead are kept. Korah and the others went down to Sheol alive. They went there directly; they did not need to die first. Hades is like a temporary jail, and the lake of fire is the final prison. These perished ones entered into the temporary jail to wait for the final imprisonment in the lake of fire. They went there without dying physically. This was something new that Jehovah created (vv. 29-30). We may say that it was a great miracle in a negative sense. In this way God used the earth to judge the rebellious ones. Probably this is the only time that living people were punished in such a way.
. Fire Coming Forth from Jehovah and Consuming the Two Hundred Fifty Men Offering the Incense
.. After the earth had swallowed the families of Korah, Dathan, and Abiram, there were still two hundred fifty followers of Korah. They were well-known leaders selected from the entire congregation. By this we can see that the rebellion was quite popular, even universal. Immediately after the three leaders were swallowed up alive by the earth, fire came forth from Jehovah and consumed the two hundred fifty men while they were offering incense (v. 35). This was the second aspect of God's judgment.
. The Censers of the Two Hundred Fifty Men Being Holy and Being Made into Hammered Plates as a Covering for the Altar
.. The two hundred fifty men were burned by God in His judgment. Then their censers were hammered into plates to cover the altar. When the people came to offer at the altar, they were reminded of the rebellion and of God's judgment on Korah and his company.
. The Exposure of the Unsubdued Rebellious Nature of the People of Israel-We may think that, after this twofold judgment, all the children of Israel would be calmed down and subdued. That, however, was not their situation.
.. On the Next Day All the Assembly of the Sons of Israel Murmuring against Moses and Aaron
	The murmuring of the people against Moses and Aaron proves that their rebellious nature had not been subdued. "On the next day all the assembly of the sons of Israel murmured against Moses and against Aaron, saying, You have killed the people of Jehovah" (v. 41). I find it incredible that they could murmur against Moses and Aaron in such a way.
.. God's Intervening
	God intervened immediately. His glory appeared in the cloud that covered the tent of meeting (v. 42). He told Moses that He would consume the assembly in a moment (vv. 43-45a), and He sent the plague to kill them under His wrath (v. 46b). The germs of the plague were probably in them already.
.. The Propitiation for the Sons of Israel through Moses and Aaron
... At this juncture, Moses and Aaron did something as an emergency measure. Moses and Aaron fell on their faces (v. 45b). Aaron put fire from the altar in the censer, placed incense on the fire, carried the censer quickly to the assembly, and stood between the dead and the living, to make propitiation for them. Then the plague was stopped. Nevertheless, fourteen thousand seven hundred of the people were killed. This was God's judgment from within the rebellious people.
... By reading chapter seventeen we can see that the remainder of the people still were not subdued. There had been a threefold, miraculous judgment by God. God had judged them by the earth, by fire from heaven, and by the plague that issued from the germs within them. Any one of those judgments should have been sufficient to subdue them and to cause them to fall down before God and worship Him. They certainly should have been subdued by the third judgment. However, even after the third judgment the people still complained (17:13). How terrible was their situation! They were so bold in their rebellion, not caring if they went to Sheol or the lake of fire, that they risked their lives, even their souls. They rebelled against Moses and Aaron, and eventually they rebelled against the very God, Jehovah. From this we see how perverse is the rebellious nature of fallen humankind.
... If we consider God's way of judging, we will see that He executes His judgment from three directions: from the earth, from heaven, and from within the rebellious ones. Rebellious people, however, are not subdued by this. Actually, according to the record of the Bible, God never has subdued people by judgment. After the thousand years of purifying in the millennium, the human race will still rebel (Rev. 20:7-9). God's judgment does not subdue people; rather, it consumes them.
... After reading a portion such as Numbers 16, some of us may have questions about God's love, mercy, kindness, and forgiveness. Why did God forgive the sinning Israelites yet still punish them? To answer this question we need to realize that, according to the teaching of the Bible, God's forgiveness is of different kinds. One kind is forgiveness through punishment. For God to forgive is one thing, and for Him to punish is another. In a particular situation God forgives, but He forgives through punishment; hence, this is a forgiveness with punishment.
... We need to have a holy fear before God. We should bow down and humble ourselves before Him and pray, "Lord, have mercy on me. Only Your mercy can preserve me and keep me in Your grace."

*In Numbers 17 we have God's vindication. Before we consider this matter, I would like to add a word concerning the descendants of Korah.*

. Numbers 16 seems to indicate that all of Korah's family, including his children, perished. But Numbers 26:11 tells us that the sons of Korah did not die. Either they did not take part in that conspiracy and rebellion, or they took Moses' word in 16:26 and departed from the tent of their father and thereby escaped the tragedy that took place when the earth opened and swallowed Korah and his company.
. In 1 Chronicles 6:33-37, a record of the genealogy of Samuel, we are told that Samuel was a descendant of Korah. Korah aspired to have a higher position in the priesthood. He did not attain it and he became rebellious. However, one of his descendants became a priest, not by struggling for power but by being offered as a Nazarite. (See Messages Eight through Ten on being sanctified to be a Nazarite.) Samuel was not only a priest but also a great prophet.
. Furthermore, as the title of Psalm 88 indicates, this psalm was written by Heman, a descendant of Korah and a grandson of Samuel (1 Chron. 6:33). Heman was not only a psalmist but also a singer in the temple under David's arrangement.
. In God's sparing Korah's descendants, we can see His mercy. One of Korah's descendants became a great prophet and took part in the priesthood. Another became one of the psalmists, a writer of one of the best psalms and a temple singer and musician. Thus, from the history recorded in the Old Testament, we can see that God is severe to some but merciful to others. Whether we experience His mercy or His severity depends on how we behave ourselves.

=== E. God's Vindication

* In chapter seventeen God went further to vindicate Aaron and Moses, His deputy authority, in a positive way.
. After His Judgment, God Commanding That Twelve Rods Be Laid before the Testimony
.. This signifies that everything had to be brought into the presence of God to let God deal with the real situation by speaking the truth to all the people through His vindication. In typology a rod signifies authority (cf. 1 Cor. 4:21). In Numbers 17 the rods represented the leaders of the twelve tribes (v. 2), and Aaron's rod represented the tribe of Levi (v. 3).
.. Jehovah said, "The rod of the man whom I choose shall bud; thus I will make to cease from Me the murmurings of the sons of Israel, which they murmur against you" (v. 5). It was God's intention that this budding of a dead rod would cause the murmurings of the people to cease.
..  Sometimes, for His vindication, God puts us into a dark night, a dark tunnel, through which we must pass.
. Aaron's Rod Budding
.. Aaron's dead, dried up rod budded. This was an organic miracle.
.. Moses brought all the rods to all the sons of Israel, and they all looked (v. 9). The record indicates that, without saying a word and without praising the Lord for His vindication, each man took his rod.
. The Budding Rod of Aaron Being Put Back before the Testimony 
.. As God Commanded Moses
	The budding rod of Aaron was put back before the testimony (v. 10). This was done according to God's commandment to Moses (v. 11).
.. To Be Kept as a Sign for the Sons of Rebellion
... The budding rod of Aaron was to be kept as a sign for the sons of rebellion, that their murmurings against God might be ended, lest they die (v. 10). Verse 5 refers to the murmurings as being against Moses, but verse 10 refers to them as being against God.
... In Numbers 16 and 17 two signs were produced through the rebellion of the sons of Israel. One was a negative sign, made of the censers of those who had been judged (16:36-40). One was a positive sign, produced by the budding rod of Aaron. The budding rod was contained in the ark with two other things—the hidden manna and the testimony of God, the law. All three items are types of Christ. The budding rod, the hidden manna, and the testimony, the law, of God all signify Christ. By this we can see that whatever happened in the Old Testament on the positive side was related to Christ.
... The budding rod of Aaron typifies not a dead Christ but the resurrected Christ, the budding Christ, who imparts life to others. Christ always flows out life to enliven others. Christ is the greatest budding rod in the universe. Today He is still budding, and we are a small part, the fruit, the almonds, of His budding.
. The Rebellious Nature of the People of Israel Being Exposed to the Uttermost
.. The rebellious nature of the people of Israel was exposed to the uttermost. After God's vindication through Aaron's budding rod, they said, "Behold, we perish, we are undone, we are all undone. Everyone shall die who comes near at all to the tabernacle of Jehovah. Shall we not all end up perishing?" (vv. 12-13). This indicates that even after seeing God's judgment and vindication, the people were not subdued.
.. It is no wonder that these children of Israel were not permitted to enter the promised land. In their rebellion, they had gone too far. 
.. As chapter seventeen reveals, this case ends with the punished people not being subdued. Therefore, even God gave them up and let them go. They simply let the people be as they were. It is good to have such a picture in typology.
.. Do not expect to see an ending of turmoil. Every "storm" will surely come to an end. In history there has never been an endless storm. Although a particular storm will end, those who become involved in that storm may not cease their rebellion.
.. The rebellious nature in man is Satan himself. Only one person, Jesus Christ, who is the Son of God and also the Son of Man, can defeat this evil one, and He has defeated him (Heb. 2:14).
.. We need to be continually on the alert by watching and praying. We have not only the Devil as the enemy on the outside but also Satan as the adversary on the inside. Since this is the situation with fallen human beings, we should not expect to see the ending of man's rebellious nature. There is no end.
.. When Paul was about to be martyred, he wrote to Timothy, in his last Epistle, saying that all the people in Asia had left him (2 Tim. 1:15). This is the sad, dark portrait in 2 Timothy. Nevertheless, Paul was triumphant (2 Tim. 4:17-18).
.. We have emphasized the fact that, even after God's judgment and vindication, the children of Israel continued to speak words of rebellion. Numbers 17 portrays a sad picture concerning this rebellion. After seeing such a picture, we can only worship God, and worship Him as the Lord.

## note
. the people
. the reason
. mose's reaction
. god's reaction
.. judgement
... heaven
... earth
... within the people
.. vindication
... rod before testmoney
... rod budding
... rod put back testmoney
... expose the rebelious nature to the uttermost

## speak