= MESSAGE NINETEEN JOURNEYING(4)

== C.Slandering
. one problem after another, the motive for quite a time

=== 1.Moses Having Married a Cushite Woman
. less message about this

=== 2.Miriam and Aaron Speaking against Moses, the Deputy Authority of God
. From this we need to learn that in the service of the Lord we should not allow anything negative to remain hidden within us. Any such thing that is not rooted out of our being will come out sooner or later. We need to be alert and aware of any germs that may still be in us. We may seem to be very good, but when certain winds begin to blow or when a particular "storm" or turmoil arises, we may be affected and involved. Then, like Miriam and Aaron, we will be exposed.
	
==== a.Because of Jealousy
. Being older than Moses, in their heart they regarded themselves higher than Moses and were jealous of the greater respect that Moses received. 
. Hence, the real issue here concerned the question of who had God's oracle. You may be used by God to speak for Him, but you may not have God's oracle.
. Actually, neither Aaron nor Miriam was God's spokesman; only one, Moses, had the oracle of God. The jealousy concerning this was the germ that caused the "sickness" in Numbers 12. Throughout the generations, the germs of jealousy and rivalry regarding speaking for the Lord have existed among God's servants.
. Because of Moses' timidity [tɪ'mɪdətɪ], God gave Aaron to Moses as his helper (Exo. 4:10-16; 6:30—7:1). However, this does not mean that He appointed Aaron to be His authority. According to God's governmental administration, Miriam and Aaron should have submitted themselves to Moses. But they rebelled.

==== b.Taking Moses' Apparent Mistake as an Excuse
. They were in rivalry with Moses. This, not the Cushite woman, was the real factor in their speaking against Moses.

=== 3.Moses Being Very Meek, More Than All Men Who Were on the Face of the Earth
. Moses was such a person; he did not fight or strive.
. It is difficult to find the frank faithfulness of one who serves God according to what God says.

=== 4.God Intervening In Numbers 12:5-9 God intervened.

==== a.Coming Down in a Pillar of Cloud and Standing at the Entrance of the Tent, Speaking to Aaron and Miriam
. To touch, defy, or challenge God's authority is to shake God's throne. This is very serious, much more serious than murmuring evil and lusting for meat.

==== b.Vindicating Moses
. God vindicated Moses as His servant, one who was faithful in all His house (v. 7). 

==== c.Rebuking Aaron and Miriam
. God rebuked Aaron and Miriam. He asked them, "Why then were you not afraid to speak against My servant, against Moses?" (v. 8b). The anger of Jehovah burned against them, and He departed from them (v. 9).

=== 5.Miriam Being Punished
. First, it is likely that Miriam took the lead in this rebellion. She was the instigator [ˈɪnstɪgeɪtə(r)], the initiator [ɪˈnɪʃieɪtə(r)], who stirred up Aaron. Miriam, not Aaron, was the main source. Second, it is not at all seemly for a female to rebel. Concerning rebellion, some allowance may be given to a male, but none should be given to a female. God punished Miriam to warn and alarm all the females among the children of Israel so that they would not follow Miriam.

==== a.Being Made Sick of Leprosy
. Miriam was leprous, as white as snow. And Aaron turned towards Miriam, and she was leprous" (v. 10). This was God's governmental dealing.

==== b.Aaron Begging Moses for Her
. we should learn from this not to follow an instigator. If we follow such a one, we may eventually have to beg on his behalf.
. In begging for Miriam, Aaron confessed their folly[ˈfɒli]. 

=== 6.Moses Praying for Miriam's Healing
. Moses prayed for Miriam's healing, saying, "Heal her, O God, I beg You" (v. 13). This is a further indication of Moses' meekness. If he had not been meek, he would not have prayed for her but instead would have let her die in her leprosy. 
. The people were delayed on the march until Miriam was brought in again (v. 15b). 
. The principle in the case of Miriam and Aaron is the same with us today. 

== note 

== background
. murmur their misfortune->burn and consume some at the ourskirts of the camp
. mixed multitude lust meat, even israel weep and want to eat meat, remember the food in egypt, have no appetite->many quails,stuck with severe [sɪˈvɪə(r)] plague [pleɪɡ]
. mose burden too heavy ->elders,assistants
. many problem
. turmoil[ˈtɜːmɔɪl]chaos

== detail

=== resson
. surface:marriage
. inner:Jealousy,rivalry [ˈraɪvlri]

=== process
. speak against
. meek,on the Face of the Earth
. Intervening  [ˌɪntəˈvi:nɪŋ]
.. 	Coming Down in pillar
..	stand at entrance
..	Vindicating [ˈvɪndɪˌkeɪtɪŋ] :meek,oracle speak face to face, [ˈɒrəkl],faithful in house
..	Rebuking [riˈbju:kɪŋ] no afraid my servant
..	Punished was leprous
. Praying for Miriam's Healing

=== result
. miriam:leprosy
. aaron:beg,folly
. mose:pray for,cry to
. all:delayed on the march 

== lesson
. should not complain, murmur circumstances, situation
. should not fill lust and appetite[ˈæpɪtaɪt]
. should not allow anything negative to remain hidden within us.
. be alert and aware of any germs[dʒɜ:rms] that may still be in us

== words
. now we come to today's topic, the failture of slandering. first we come to the background of this failture. in the foregoing message we have seen that there are so many problems, one after another. first the people of the skirtout of the camp murmur evils.
the complain their circumtance and situation. maybe they say that they are so bitter. live is suffering. then god's anger was kindled and god make fire to cusume them. then the mixed multitudes lusting meat, even the children of israel also want to eat meat. they feel
that the manna is tasteless, they have no appetite, they want to eat meat. and they rememer
the food which the eat at egypt. the god give them many quails, and a servery plague come to them. and mose also said that his burden is so heavy, he can't bear. and he marrage a cusite woman, these things make the situation become turmoil and chaos. 
. at this juncture, annan and his sister miriam speak against mose. reproach that mose have married a cusite woman. but the marrage is not the true reason, the real reason is
their jealousy, the want to receive more respect than mose. the compete with mose, this is a rivalry. they speaked that it is not only god speak to mose, but also speak to them.
. face this situation, mose is very meek, he didn't struggle or strive. but god comed down in the pillar of cloud and stood at the entrance of the camp. he was vidicating for mose, god said that he speaks with mose face to face, mose is faithful in his house. he was rebuting them by said that you are no afraid to speak against my servant? then depart from them, and miriam become leperous. as white as snow.
. annan beged for his sister to mose, and mose cried to god, and pray for her. but it needs seven days to cure her leper. and the march was delayed by her.
. from this failture, we need to learn some lessons. first we should not complain or murmur our situation. second we should not fill our lust and appetite. if we lust meat, we wil be punished by plague. third we should not allow any nigative thins hidden in our inner being, we need alert and aware of any germs within us. because they will be exposed in the future. we need god to deal with the germs in us.  